# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c37ee8b2a95701efff86c8306ab8820f3ac2053f7bf59795a3c950529cf7f6f1bc0b02988b2c635e0da60165272e801592312e14e0ef7da74c9848c79e636e81

test:
  secret_key_base: b2054ed1e4fdc4c8acbe25ecb607d1783633a4cfe174769135b209eec5d96f4f6b024baa62c4c2211f7aacc43187fcff528f56a20aef952bd637db98a3aba80b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
